version: '3'

services:
  db:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: asdf
      POSTGRES_DB: 'asdf'

  app:
    build: '.'
    restart: always
    ports:
      - '8000:8000'

    volumes:
      - './:/app'
  